### ISSUE TITLE
/stakeholders/:id path is broken

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-stakeholder-api#15]
https://dev-k8s.treetracker.org/stakeholder/stakeholders/a8567323-88b1-4870-8c48-68d2da3ab356
```

error: select "s".* from "stakeholder" as "s" left join "stakeholder_relation" as "sr" on "s"."id" = "sr"."child_id" where "s"."id" = $1 or "s"."owner_id" = $2 and "sr"."child_id" is null order by "s"."org_name" asc limit $3 - column s.owner_id does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by ZavenArra** [comment]
What is the purpose of owner_id here?  I am not aware of a the stakeholder needing an owner_id attribute

**Comment by gwynndp** [comment]
We removed the owner_id from the api.
